# Generated by Django 5.2.8 on 2025-12-04 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='AddStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_domestic_cylinder', models.PositiveIntegerField(default=0)),
                ('domestic_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('no_commercial_cylinder', models.PositiveIntegerField(default=0)),
                ('commercial_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('return_domestic_cylinder', models.PositiveIntegerField(default=0)),
                ('return_commercial_cylinder', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.vendor')),
            ],
        ),
    ]
