# Generated by Django 5.2.8 on 2025-12-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_domestic_cylinder', models.PositiveIntegerField(default=0)),
                ('no_commercial_cylinder', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
