# Generated by Django 5.2.8 on 2025-12-04 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0003_alter_addstock_vendor_delete_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstock',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
