# Generated by Django 5.2.8 on 2026-01-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0004_addstock_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstock',
            name='price_per_commercial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='addstock',
            name='price_per_domestic',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
