# Generated by Django 5.2.6 on 2025-09-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
