# Generated by Django 5.2.6 on 2025-10-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
