# Generated by Django 5.2.6 on 2025-09-05 17:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_domestic_cylinder', models.PositiveIntegerField(default=0)),
                ('domestic_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('no_commercial_cylinder', models.PositiveIntegerField(default=0)),
                ('commercial_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('return_domestic_cylinder', models.PositiveIntegerField(default=0)),
                ('return_commercial_cylinder', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('date', models.DateField(default=datetime.date.today)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='customer.customer')),
            ],
        ),
    ]
