# Generated by Django 5.2.6 on 2025-09-05 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
