# Generated by Django 5.2.8 on 2025-11-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_alter_sell_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('due', 'Due'), ('partialy', 'Partialy')], default='due', max_length=20),
        ),
    ]
