# Generated by Django 5.2.8 on 2025-11-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0003_sell_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
